src/window.py
The icon did not appear in panels of XFCE, LXQt, and possibly MATE.
Similar issues have been reported in https://github.com/rafaelmardojai/blanket/issues/54 and https://github.com/rafaelmardojai/blanket/issues/84 .
The fix is this https://github.com/rafaelmardojai/blanket/commit/b3d0f92f97286cd5055b6e7abba29a4adad0f568
I have verified that it works in XFCE.
Before
After
(the different icon is due to Papirus Icon theme)
=> Fix missing icon in XFCE, LXQt

README.md
The spec file follows the [Fedora Packaging Guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/). Here it is:
<details open>
```spec
%global         appid com.github.hugolabe.Wike
Name:           wike
Version:        1.5.3
Release:        1%{?dist}
Summary:        Wikipedia Reader for the GNOME Desktop 
License:        GPLv3
URL:            https://github.com/hugolabe/wike
Source0:        %{url}/archive/%{version}/%{name}-%{version}.tar.gz
BuildArch:      noarch
BuildRequires:  meson
BuildRequires:  python3-devel
BuildRequires:  python3-gobject-devel
BuildRequires:  libhandy1-devel
BuildRequires:  gettext
BuildRequires:  desktop-file-utils
BuildRequires:  libappstream-glib
Requires:       hicolor-icon-theme
Requires:       python3-gobject
Requires:       gtk3
Requires: …
```
=> Add Fedora (Copr) package

data/ui/shortcuts.ui, src/window.py
I chose `Alt+R` to be consistent with the `Alt+Home` shortcut. `Ctrl+R` is already in use. I also removed the `max-height` property to prevent the "Navigation" section from being displayed in a different tab:
I could increase the `max-height` to 13 or 14, but it doesn't seem necessary to have it.
Closes #95
=> Add random article shortcut

data/com.github.hugolabe.Wike.metainfo.xml.in
This will also help apps.gnome.org and other GNOME tools to automatically collect data
=> data: Add bugtracker to metainfo

po/fr.po
French language typo needs fixing: acceuil => accueil
=> Fix typo in fr.po

data/ui/headerbar.ui
The HIG recommends the use of "Back" and "Forward" for these navigation buttons and recommends the use of "Main Menu" for the primary menu.
=> headerbar: Add missing tooltips

src/header.py, src/window.py
As the headerbar will receive its layout update when the window is (re-)allocated its default is only used for measurement of this widget.
Therefore, it should reflect the state with minimal width to properly work with the height for width way GTK uses for allocating space.
depends on and includes ceb38a3642923eef895dbc792e894151c1fdb47e from the current develop branch
fixes #122
=> fix adaptive headerbar for maximised state

src/view.py
WebKitGTK has a simple flag to enable gestures to navigate back and forward.
They can be used with Wike as is, as e.g. Wike's history seems to be updated correctly.
=> enable gestures to navigate back/forward in WebView

data/ui/window.ui, src/window.py
This is a follow-up to #118.
> The pin-sidebar action's state, being user intend for a pinned sidebar, can and will be overruled for lack of space. Currently, this overruling is made permanent, so shrinking the window and re-expanding it will result in the previously pinned sidebar to not be pinned anymore.
> 
> With decoupling the flap state from the pin-sidebar action, this overruling is made temporary with the user's previous setting restored.
> 
> As a follow-up, the button to pin the sidebar is when disabled of no use, and could even confuse due to the button's state not reflecting the sidebar's state. To solve this confusion, the button can be hidden, when the sidebar is forced into the collapsed mode on smaller screens or window widths.
changes since v1:
* sidebar page toggle …
=> [v2] decouple flap state from pin-sidebar action to restore pinned state after re-expanding window

.github/workflows/flatpak.yml
As suggested in https://github.com/hugolabe/Wike/issues/122#issuecomment-1513584530, it would be great if there were a CI pipeline building it and providing downloadable flatpak bundles.
=> add CI to build flatpaks

data/com.github.hugolabe.Wike.gschema.xml, data/ui/prefs.ui, src/application.py, src/prefs.py
Closes #115, Closes #114
Added a toggle to the personal data row in the preferences dialog to add the option to clear cache and cookies when the application is closed. Let me know if you would prefer a different UI.
Screenshot:
=> Add option to clear cache and cookies when Wike is closed

data/com.github.hugolabe.Wike.metainfo.xml.in
GNOME automatically excludes release descriptions on Damned Lies (GNOME Translation Platform). It's a good practice to follow the GNOME way.
This can streamline the translation process, allowing translators to focus their efforts on more critical and user-facing aspects of the application.
=> data: Mark release descriptions as untranslatable

data/com.github.hugolabe.Wike.metainfo.xml.in
These URL is visible on Flathub and GNOME Control Center.
More information: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-url
=> appdata: add vcs-browser support

data/com.github.hugolabe.Wike.metainfo.xml.in
This metadata is invalid: custom data is a dictionary and using the same key multiple times in a dictionary does not work
More information: https://github.com/ximion/appstream/issues/476
=> appdata: Remove Purism metadata

build-aux/flatpak/com.github.hugolabe.Wike.json, data/com.github.hugolabe.Wike.gschema.xml, data/ui/prefs.ui, src/application.py, src/page.py, src/window.py
This would fix #100.
The app is a little bit laggy for me during the first seconds when opening several pages, but nothing too bad; and I guess the trade-off is worth it! I tried to add the pages via `GLib.idle_add` too to see if it would increase performances, but it does not.
It also switches to the latest opened tab when opening them, so it effectively restores the last session nearly entirely.
=> Add a 'Restore window' option

data/com.github.hugolabe.Wike.metainfo.xml.in, data/meson.build
appstream-util is obsoleted by appstreamcli.
Add categories and keywords.
Entries are copied from the desktop file.
=> Appdata related patches

.github/workflows/flatpak.yml
- Bump `actions/checkout` from `v3` to `v4` the changes can be found [here](https://github.com/actions/checkout/compare/v3...v4), this includes **Node 20**
- Bump `docker/setup-qemu-action` from `v2` to `v3`, changes can be found [here](https://github.com/docker/setup-qemu-action/compare/v2.2.0...v3.0.0)
-  Bump `bilelmoussaoui/flatpak-github-actions/flatpak-builder` from `v6.1` to `v6.3`
=> CI: Bumped Checkout (v4), Flatpak Builder (v6.3) & Setup Qemu Action (v3)

data/ui/history-row.ui, src/data.py, src/history.py
This fixes #101.
I was heavily inspired by your implementation of bookmark remove buttons, however the implementation is a little bit different because of the way the history needs to allow uri duplicates, etc
It seems to work all right for me, maybe some additional testing would be better though (as I may have not though about all the edge cases).
By the way, sorry for my urge to make pull requests for your app, I just love using it and wanted to give it a little bit back!
=> Add a remove button for history row

data/com.github.hugolabe.Wike.metainfo.xml.in
The ID "github.com" does not uniquely identify you, Hugo Olabera, as a developer. As such, it is not a correct one.
Furthermore, the documentation for AppStream was updated to clarify how the id is supposed to look, and recommends the use of reverse-DNS, or of ActivityPub handles.
Link: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer
=> use correct developer ID in AppStream meta data

data/com.github.hugolabe.Wike.metainfo.xml.in
It appears that the appstream project no longer supports `translatable=no` properties, and gettext extract the `translatable=no` marked strings as translatable.
I opened an issue to inform about the situation, but `translatable=no` properties are not accepted by developers. You can find the issue here: https://github.com/ximion/appstream/issues/623
**Please test your script or string extraction process before merging this PR.**
> In MetaInfo files, each individual paragraph of a description
> (or enumerated entry) is translated individually, however,
> you can only exclude the complete block from being translated
> by adding `translate="no"` to the description element.
Source: https://freedesktop.org/software/appstream/docs/sect-Quickstart-Translation.html
=> appdata: `translate=no` properties
